Site/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Site.Models;
using System.Data.Entity;
using Newtonsoft.Json;
using ConsumedByCode.SignatureToImage;

namespace Site.Controllers
{
    public class WorkController : Controller
    {
        public ActionResult Index(Guid? crewId = null)
        {
            using (var context = new WorkOrderContext()) {
                if (!context.WorkOrders.Any(w => w.Date >= DateTime.Today)) {
                    context.Reset();
                }

                if (!(crewId.HasValue)) {
                    var crews = context.Crews.OrderBy(c => c.Name).ToList();
                    var model = new ChooseCrewModel { Crews = crews };

                    return View("ChooseCrew", model);
                }

                var crew = context.Crews.FirstOrDefault(c => c.Id == crewId.Value);

                var workOrders = context.WorkOrders
                    .Include(w => w.Crew)
                    .Include(w => w.Category)
                    .Include(w => w.WorkOrderLogs)
                    .Where(w => !w.IsComplete && w.CrewId == crewId.Value)
                    .ToList();

                var viewModel = new CrewListViewModel(crew, workOrders);

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Index(WorkOrderLog input, Guid crewId, bool isComplete)
        {            
            using (var context = new WorkOrderContext()) {

                var workOrder = context.WorkOrders.Include(w => w.WorkOrderLogs).First(w => w.Id == input.WorkOrderId);
                workOrder.IsComplete = isComplete;

                var signatureValue = Request.Form["Signature"];
                if (!string.IsNullOrEmpty(signatureValue)) {
                    var signature = JsonConvert.DeserializeObject<Signature>(signatureValue);
                    var converter = new SignatureToImage();
                    var image = converter.SigJsonToImage(signatureValue);
                }

                if (!workOrder.WorkOrderLogs.Any()) {
                    input.Date = DateTime.Now;
                    workOrder.WorkOrderLogs.Add(input);
                } else {
                    var log = workOrder.WorkOrderLogs.First();
                    log.Date = DateTime.Now;
                    log.Notes = input.Notes;
                }

                context.SaveChanges();

                return RedirectToAction("Index", new { crewId = crewId });
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            using (var context = new WorkOrderContext()) {
                var workOrder = context.WorkOrders.Include(w => w.WorkOrderLogs).FirstOrDefault(w => w.Id == id);

                var log = workOrder.WorkOrderLogs.FirstOrDefault() ?? new WorkOrderLog();

                var viewModel = new EditWorkItemViewModel {
                    Id = log.Id,
                    WorkOrderId = workOrder.Id,
                    Title = "Enter work for work order",
                    Date = workOrder.DateDisplay,
                    Customer = workOrder.Customer,
                    Description = workOrder.Description,
                    Duration = workOrder.Duration,
                    Notes = log.Notes,
                    CrewId = workOrder.CrewId.Value,
                    IsComplete = workOrder.IsComplete
                };

                return View(viewModel);

            }
        }
    }
}

Site/Views/Work/ChooseCrew.cshtml
@model Site.Models.ChooseCrewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Choose Crew</title>
        <link rel="stylesheet" type="text/css" href="~/css/modern.css" />
        <link rel="stylesheet" type="text/css" href="~/css/modern-responsive.css" />
        <link rel="stylesheet" type="text/css" href="~/css/app.css" />

        <script type="text/javascript" src="/js/jquery-1.9.0.js"></script>

        <style>
        .tile.crew { width: 150px; }
        </style>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-40200465-1']);
            _gaq.push(['_trackPageview']);

            (function () {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body class="metrouicss">
        <div class="page">
        <div class="page-header">
            <div class="page-header-content">
                <h1>Choose Crew</h1>                
            </div>
        </div>
        <div class="page-region">
            <div class="page-region-content">
                <p>(Normally, you would log in to see your work orders.)</p>

                <div class="clearfix">
                    @foreach (var crew in Model.Crews) {
                        <a class="tile crew" href="@Url.Action("Index", new { CrewId = crew.Id })">
                            <div class="tile-content">
                                <img src="~/img/Crew.png" alt="Crew" />
                            </div>
                            <div class="brand">
                                <span class="name">@crew.Name</span>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
    </body>
</html>

Site/Views/Work/Edit.cshtml
@model Site.Models.EditWorkItemViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/modern.css" />
    <link rel="stylesheet" type="text/css" href="~/css/modern-responsive.css" />
    <link rel="stylesheet" type="text/css" href="~/css/app.css" />
    <link rel="stylesheet" type="text/css" href="~/css/jquery.signaturepad.css" />

    <style>
        .sigWrapper {
          clear: both;
          height: 100px;
        }
        .sigPad {
            width: 500px;
        }
        canvas.pad {
            width: 500px;
            height: 95px;
        }
    </style>

    <script type="text/javascript" src="/js/jquery-1.9.0.js"></script>
    <script type="text/javascript" src="~/js/jquery.signaturepad.min.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="metrouicss">
    <div class="page secondary">
        <div class="page-header">
            <div class="page-header-content">
                <h1>@Model.Title</h1>
                <a href="@Url.Action("Index")" class="back-button big page-back"></a>
            </div>
        </div>
        <div class="page-region">
            <div class="page-region-content">
                @using(Html.BeginForm("Index", "Work")) {
                    
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.WorkOrderId)
                    @Html.HiddenFor(m => m.CrewId)

                    <label>Date:</label>
                    <div class="input-control text span2">
                        <span>@Model.Date</span>
                    </div>
                    
                    <label>Customer:</label>
                    <div class="input-control text span5">
                        <span>@Model.Customer</span>
                    </div>
                    
                    <label>Description:</label>
                    <div class="input-control textarea span7">
                        <span>@Model.Description</span>
                    </div>
                    
                    <label>Duration:</label>
                    <div class="input-control select span2">
                        <span>@Model.Duration</span>
                    </div>
                    
                    <label>Work Done:</label>
                    <div class="input-control textarea span7">
                        <textarea name="Notes" rows="5" autofocus>@Model.Notes</textarea>
                    </div>

                    <label class="input-control checkbox span7">
                        @Html.CheckBoxFor(m => m.IsComplete, new { @class = "complete" })
                        <span class="helper">Job Complete?</span>
                    </label>                
                    
                    <label class="signature no-display">Signature:</label>
                    <div class="input-control span7 signature no-display">
                        <div class="sig sigWrapper">
                            <canvas class="pad" width="500" height="95"></canvas>
                            <input type="hidden" name="signature" class="output">
                        </div>
                        <a class="clear" href="#">Clear</a>
                    </div>
                    
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "button" })
                    <input type="submit" value="Save" class="button" />
                }
            </div>
        </div>
    </div>    
    <script type="text/javascript">
        $(function () {
            var sigPad = $('form').signaturePad({ drawOnly: true, clear: 'a.clear', lineTop: 65 });

            $('input:checkbox.complete').click(function (e) {
                var method = e.currentTarget.checked ? 'removeClass' : 'addClass';
                $('.signature')[method]('no-display');
            });
        });
    </script>
</body>
</html>

Site/Views/Work/Index.cshtml
@model Site.Models.CrewListViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
    <link rel="stylesheet" href="~/css/modern.css" />
    <link rel="stylesheet" href="~/css/modern-responsive.css" />
    <link rel="stylesheet" href="~/css/app.css" />

    <script src="/js/jquery-1.9.0.js"></script>
    <script src="/js/scrollToFixed.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="crew-list metrouicss">
    <div class="tour-wrapper">        
        <section class="message info-bar">
            <button class="hide-tour place-right tool-button toolbar"><i class="icon-cancel-2"></i> </button>
            <p>This page shows you a day-by-day listing of what work a particular crew is scheduled to do.</p>
            <p>You can click any of the tiles to enter the work done, and indicate whether the job is done.</p>
            <p>Click here to see the <a href="/WorkOrders#tour" class="button"><i class="icon-calendar"></i>Master Schedule</a> list.</p>
        </section>
        <section class="content">
            <div class="page">
                <div class="page-header">
                    <div class="page-header-content">
                        <h1>@Model.Title</h1>
                        <button class="show-tour place-right"><i class="icon-comments-5"></i> Show Page Info</button>
                    </div>
                </div>
                <div class="page-region">
                    <div class="page-region-content">
                
                        @Html.Partial("~/Views/Work/DisplayTemplates/CrewListHeader.cshtml", Model)
                
                        <section class="day">
                            @foreach (var day in Model.Days) {
                                @Html.Partial("~/Views/Work/DisplayTemplates/CrewListDayModel.cshtml", day);
                            }
                        </section>

                    </div>
                </div>
            </div>
        </section>
    </div>
    <script type="text/javascript">
        $(function () {
            if (window.location.hash.indexOf('tour') === -1) {
                $('header').scrollToFixed();
            } else {
                $('.tour-wrapper').addClass('tour');
                window.setTimeout(function () {
                    $('header').scrollToFixed({ marginTop: 150, zIndex: 1003 });
                }, 250);
            }

            $('.show-tour').click(function (e) {
                e.preventDefault();

                $('.tour-wrapper').addClass('tour');
                window.location.hash = 'tour';
                $('header').trigger('detach.ScrollToFixed').scrollToFixed({ marginTop: 150, zIndex: 1003 });
            });

            $('.hide-tour').click(function (e) {
                e.preventDefault();

                $('.tour-wrapper').removeClass('tour');
                window.location.hash = '';
                $('header').trigger('detach.ScrollToFixed').scrollToFixed();
            });
        });
    </script>
</body>
</html>