Site/Models/WorkOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Models
{
    public class WorkOrder
    {
        public Guid Id { get; set; }
        public DateTime? Date { get; set; }
        public String Customer { get; set; }
        public Guid? CrewId { get; set; }
        public String Description { get; set; }
        public Guid CategoryId { get; set; }
        public bool IsComplete { get; set; }
        public String Duration { get; set; }

        public WorkOrderCategory Category { get; set; }
        public Crew Crew { get; set; }
        public ICollection<WorkOrderLog> WorkOrderLogs { get; set; }

        public string AssignedTo
        { 
            get 
            { 
                return Crew == null ? "Unassigned" : Crew.Name; 
            } 
        }

        public string DateDisplay
        {
            get
            {
                return Date.HasValue ?
                    Date.Value.ToString("dd-MMM-yyyy hh:mm") :
                    string.Empty;

            }
        }
    }
}

Site/Controllers/WorkOrdersController.cs
using Site.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;

namespace Site.Controllers
{
    public class WorkOrdersController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            using (var context = new WorkOrderContext()) {

                if (!context.WorkOrders.Any(w => w.Date >= DateTime.Today)) {
                    context.Reset();
                }

                var workOrders = context.WorkOrders
                    .Include(w => w.Crew)
                    .Include(w => w.Category)
                    .Include(w => w.WorkOrderLogs)
                    .ToList();

                var viewModel = new BossListViewModel(workOrders);
                return View(viewModel);
            }
        }

        public ActionResult New()
        {
            using (var context = new WorkOrderContext()) {
                var crews = context.Crews.OrderBy(c => c.Name).ToList();
                var categories = context.WorkOrderCategories.OrderBy(c => c.Name).ToList();
                var durations = new string[] { "", "1h", "2h", "4h", "1d", "2d", "3d", "4d", "5d" };
                var viewModel = new NewWorkOrderViewModel { 
                    Title = "New Work Order", 
                    Date = DateTime.Today.ToString("dd-MMM-yyyy"),
                    Crews = crews,
                    Durations = durations,
                    Categories = categories
                };
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Index(WorkOrder input)
        {
            using(var context = new WorkOrderContext()) {
                input.Id = Guid.NewGuid();
                context.WorkOrders.Add(input);                

                if (input.Duration.EndsWith("d", StringComparison.InvariantCultureIgnoreCase)) {
                    var duration = default(int);
                    if (int.TryParse(input.Duration.Replace("d", ""), out duration)) {
                        duration--;
                        var days = 1;
                        var date = input.Date.HasValue ? input.Date : (null as DateTime?);
                        while (days <= duration) {

                            if (date.HasValue) {
                                date = date.Value.AddDays(1);
                                if(date.Value.DayOfWeek == DayOfWeek.Saturday){
                                    date = date.Value.AddDays(2);
                                }

                                if (date.Value.DayOfWeek == DayOfWeek.Sunday) {
                                    date = date.Value.AddDays(1);
                                }
                            }

                            var nextWorkOrder = new WorkOrder {
                                Id = Guid.NewGuid(),
                                CategoryId=input.CategoryId,
                                CrewId=input.CrewId,
                                Customer=input.Customer,
                                Description=input.Description,
                                Duration=input.Duration,
                                Date = date
                            };
                            context.WorkOrders.Add(nextWorkOrder);

                            days++;
                        }
                    }
                }

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid? id = null)
        {
            if (!id.HasValue) return new HttpNotFoundResult();

            using (var context = new WorkOrderContext()) {
                var workOrder = context.WorkOrders.First(wo => wo.Id == id);

                var crews = context.Crews.OrderBy(c => c.Name).ToList();
                var categories = context.WorkOrderCategories.OrderBy(c => c.Name).ToList();
                var durations = new string[] { "", "1h", "2h", "4h", "1d", "2d", "3d", "4d", "5d" };

                var crewId = workOrder.CrewId ?? crews[0].Id;

                var viewModel = new EditWorkOrderViewModel {
                    Id = workOrder.Id,
                    Title = "Edit Work Order",
                    Date = workOrder.DateDisplay,
                    Customer = workOrder.Customer,
                    Description = workOrder.Description,
                    CrewId = crewId,
                    Crews = crews,
                    Duration = workOrder.Duration,
                    Durations = durations,
                    CategoryId = workOrder.CategoryId,
                    Categories = categories
                };

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Save(Guid? id, WorkOrder input)
        {
            using (var context = new WorkOrderContext()) {
                context.Entry(input).State = System.Data.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        public ActionResult Reset()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Reset(bool reset)
        {
            if (reset) {
                using (var context = new WorkOrderContext()) {
                    context.Database.SqlQuery<int>("DELETE dbo.WorkOrderLogs");
                    context.Database.SqlQuery<int>("DELETE dbo.WorkOrders");
                    context.Database.SqlQuery<int>("DELETE dbo.Crews");
                    context.Database.SqlQuery<int>("DELETE dbo.WorkOrderCategories");
                    context.Database.SqlQuery<int>("DELETE dbo.__MigrationHistory");
                    context.Database.Initialize(true);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

Site/Views/WorkOrders/Edit.cshtml
@model Site.Models.EditWorkOrderViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/modern.css" />
    <link rel="stylesheet" type="text/css" href="~/css/modern-responsive.css" />
    <link rel="stylesheet" type="text/css" href="~/css/app.css" />

    <script src="/js/jquery-1.9.0.js"></script>
    <script src="/js/moment.js"></script>
    <script src="/js/calendar.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="metrouicss">
    <div class="page secondary">
        <div class="page-header">
            <div class="page-header-content">
                <h1>@Model.Title</h1>
                <a href="@Url.Action("Index")" class="back-button big page-back"></a>
            </div>
        </div>
        <div class="page-region">
            <div class="page-region-content">
                @using(Html.BeginForm("Save", "WorkOrders")) {
                    @Html.HiddenFor(m => m.Id)

                    <label>Customer:</label>
                    <div class="input-control text span5">
                        <input type="text" name="Customer" value="@Model.Customer" />
                    </div>

                    <label>Date:</label>
                    <div class="input-control text span5">
                        <input type="hidden" name="Date" value="@Model.Date" />
                        <div class="calendar" data-lang="en"></div>
                    </div>
                    
                    <label>Duration:</label>
                    <div class="input-control select span2">
                        @Html.DropDownListFor(wo => wo.Duration, Model.Durations.Select(d => new SelectListItem{ Text = d, Value = d }))
                    </div>
                    
                    <label>Crew:</label>
                    <div class="input-control select span5">
                        @Html.DropDownListFor(wo => wo.CrewId, new SelectList(Model.Crews, "Id", "Name"))
                    </div>
                    
                    <label>Description:</label>
                    <div class="input-control textarea span7">
                        <textarea name="Description" rows="5">@Model.Description</textarea>
                    </div>
                    
                    <label>Category:</label>
                    <div class="input-control select span2">
                        @Html.DropDownListFor(wo => wo.CategoryId, new SelectList(Model.Categories, "Id", "Name"))
                    </div>
                                        
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "button" })
                    <input type="submit" value="Save" class="button" />
                }
            </div>
        </div>
    </div>    
    <script>
        $(function () {
            var $calendar = $('div.calendar'),
                $hidden = $('input:hidden[name=Date]');
                
            $calendar.calendarSetDate($hidden.val());
            $calendar.init();
            $calendar.on('date-selected', function (el, dateString, dateMoment) {
                $hidden.val(dateString);
            });
        });
    </script>
</body>
</html>

Site/Views/WorkOrders/Index.cshtml
@model Site.Models.BossListViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
    <link rel="stylesheet" href="/css/modern.css" />
    <link rel="stylesheet" href="/css/modern-responsive.css" />
    <link rel="stylesheet" href="/css/app.css" />

    <script src="/js/jquery-1.9.0.js"></script>
    <script src="/js/scrollToFixed.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="boss-list metrouicss">
    <div class="tour-wrapper">        
        <section class="message info-bar">
            <button class="hide-tour place-right tool-button toolbar"><i class="icon-cancel-2"></i> </button>
            <p>This page shows you a day-by-day listing of which crews are scheduled to do what work.</p>
            <p>You can click the <a href="@Url.Action("New")" class="button new"><i class="icon-plus"></i> New Work Order</a>
            button, or any of the existing Work Order tiles in the list.</p>
            <p>Click here to see the view that your <a href="/Work#tour" class="button new"><i class="icon-user-2"></i>Crews</a> will see.</p>
        </section>
        <section class="content">
            <div class="page">
                <div class="page-header">
                    <div class="page-header-content">
                        <h1>@Model.Title</h1>
                        <button class="show-tour place-right"><i class="icon-comments-5"></i> Show Page Info</button>
                    </div>
                </div>
                <div class="page-region">
                    <div class="page-region-content">
                
                        @Html.Partial("~/Views/WorkOrders/DisplayTemplates/BossListHeader.cshtml", Model)
                    
                        @foreach (var day in Model.Days) {
                            @Html.Partial("~/Views/WorkOrders/DisplayTemplates/BossListDayModel.cshtml", day);
                        }
                
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script type="text/javascript">
    $(function () {
        if (window.location.hash.indexOf('tour') === -1) {
            $('header').scrollToFixed();
        } else {
            $('.tour-wrapper').addClass('tour');
            window.setTimeout(function () {
                $('header').scrollToFixed({ marginTop: 150, zIndex: 1003 });
            }, 250);
        }

        $('.show-tour').click(function (e) {
            e.preventDefault();

            $('.tour-wrapper').addClass('tour');
            window.location.hash = 'tour';
            $('header').trigger('detach.ScrollToFixed').scrollToFixed({ marginTop: 150, zIndex: 1003 });
        });

        $('.hide-tour').click(function (e) {
            e.preventDefault();

            $('.tour-wrapper').removeClass('tour');
            window.location.hash = '';
            $('header').trigger('detach.ScrollToFixed').scrollToFixed();
        });
    });
    </script>
</body>
</html>

Site/Views/WorkOrders/New.cshtml
@model Site.Models.NewWorkOrderViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/modern.css" />
    <link rel="stylesheet" type="text/css" href="~/css/modern-responsive.css" />
    <link rel="stylesheet" type="text/css" href="~/css/app.css" />

    <script type="text/javascript" src="/js/jquery-1.9.0.js"></script>
    <script src="/js/moment.js"></script>
    <script src="/js/calendar.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="metrouicss">
    <div class="page secondary">
        <div class="page-header">
            <div class="page-header-content">
                <h1>@Model.Title</h1>
                <a href="@Url.Action("Index")" class="back-button big page-back"></a>
            </div>
        </div>
        <div class="page-region">
            <div class="page-region-content">
                @using(Html.BeginForm("Index", "WorkOrders")) {
                        
                    <label>Customer:</label>
                    <div class="input-control text span5">
                        <input type="text" name="Customer" />
                    </div>
                    
                    <label>Date:</label>
                    <div class="input-control text span5">
                        <input type="hidden" name="Date" value="@Model.Date" />
                        <div class="calendar"></div>
                    </div>
                    
                    <label>Duration:</label>
                    <div class="input-control select span2">
                        @Html.DropDownListFor(wo => wo.Duration, Model.Durations.Select(d => new SelectListItem{ Text = d, Value = d }))
                    </div>
                    
                    <label>Crew:</label>
                    <div class="input-control select span5">
                        @Html.DropDownListFor(wo => wo.CrewId, new SelectList(Model.Crews, "Id", "Name"))
                    </div>
                    
                    <label>Description:</label>
                    <div class="input-control textarea span7">
                        <textarea name="Description" rows="5"></textarea>
                    </div>
                    
                    <label>Category:</label>
                    <div class="input-control select span2">
                        @Html.DropDownListFor(wo => wo.CategoryId, new SelectList(Model.Categories, "Id", "Name"))
                    </div>                                        
                    
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "button big" })
                    <input type="submit" value="Save" class="button big" />
                }
            </div>
        </div>
    </div>    
    <script>
        $(function () {
            var $calendar = $('div.calendar'),
                $hidden = $('input:hidden[name=Date]');

            $calendar.calendarSetDate($hidden.val());
            $calendar.init();
            $calendar.on('date-selected', function (el, dateString, dateMoment) {
                $hidden.val(dateString);
            });
        });
    </script>
</body>
</html>

Site/Views/WorkOrders/Reset.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Reset Data</title>
    <link rel="stylesheet" type="text/css" href="~/css/modern.css" />
    <link rel="stylesheet" type="text/css" href="~/css/modern-responsive.css" />
    <link rel="stylesheet" type="text/css" href="~/css/app.css" />

    <script type="text/javascript" src="/js/jquery-1.9.0.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-40200465-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="metrouicss">
    <div class="page secondary">
        <div class="page-header">
            <div class="page-header-content">
                <h1>Reset Data</h1>
                <a href="@Url.Action("Index")" class="back-button big page-back"></a>
            </div>
        </div>
        <div class="page-region">
            <div class="page-region-content">
                @using(Html.BeginForm("Reset", "WorkOrders")) {
                        
                    <input type="hidden" name="reset" value="true" />
                    
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "button" })
                    <input type="submit" value="Reset" class="button" />
                }
            </div>
        </div>
    </div>    
</body>
</html>